services:
  db:
    ports:
      - "3306:3306"
    image: mysql:8.0.38
    container_name: mysql_monitor
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: monitor
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redit_monitor
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbit_monitor
  influx:
    image: influxdb:2
    ports:
        - 8086:8086
    volumes:
        - type: volume
          source: influxdb2-data
          target: /var/lib/influxdb2
        - type: volume
          source: influxdb2-config
          target: /etc/influxdb2
volumes:
  mysql_data:
  influxdb2-data:
  influxdb2-config: