spring:
  profiles:
    active: dev
  application:
    name: boot-backend
  security:
    jwt:
      key: example
      expires: 168
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  data:
    redis:
      host: localhost
      port: 6379
    jdbc:
      dialect: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
    host: smtp.gmail.com
    port: 587
    username: ${cong.mail.username}
    password: ${cong.mail.password}

logging:
  level:
    root: info